### PR TITLE
feat: npm run info displays info on OS, env, and packages

### PR DESCRIPTION
**Pull request by scampiuk**
* Updated README.md
* added `npm run info` to display set of system information in the console for debugging reasons

### CODE REVIEW

**Comment by scampiuk** [comment]
PR for #9

**Comment by scampiuk** [comment]
PR for issue #9

**Comment by dantehemerson** [comment]
Thanks @scampiuk this looks great. Just we need to add this to the **CLI**, you can create a new module **os** with similar similar to **network** module. 


image

**Comment by scampiuk** [comment]
Interesting, didn't pick that up from the original ticket! 

I moved into it's own module 
```shell
chris@ideapad ~/sites/fons % npm run console

> fons@0.2.0 console /home/chris/sites/fons
> node dist/main.js

Usage: main [options] [command]

Options:
  -h, --help      display help for command

Commands:
  audio|a         Control output and input audio devices
  network|n       Network commands
  os|o            OS commands
  help [command]  display help for command

```

```shell
chris@ideapad ~/sites/fons % node dist/main.js o     
Usage: main os|o [options] [command]

OS commands

Options:
  -h, --help      display help for command

Commands:
  info|i         Get OS info
  help [command]  display help for command

```

I've not worked with nest before (for whatever reason) so it's interesting to see how it glues things together

**Review by dantehemerson — APPROVED** [review]
LGTM, Thanks @scampiuk :+1:

**Pull request merged**
